name: SxL-lev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

concurrency:
  group: nodejs-app  # This ensures that jobs are grouped
  cancel-in-progress: true  # This will cancel any in-progress job

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DATABASE_URL: "postgresql://postgres.llvmgvwegiyfwbeqezbp:1KIXQhl788Uu16AR@aws-0-us-west-1.pooler.supabase.com:6543/postgres"  # Replace with your actual database URL

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: start
      run: npm start
