name: SxL-lev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

concurrency:
  group: nodejs-app  # This ensures that jobs are grouped
  cancel-in-progress: true  # This will cancel any in-progress job

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Define the DATABASE_URL variable

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: start
      run: npm start
